ci(actions): :construction_worker: checking code coverage

diff --git a/.github/workflows/deploy_buddies_ci.yml b/.github/workflows/deploy_buddies_ci.yml
--- a/.github/workflows/deploy_buddies_ci.yml
+++ b/.github/workflows/deploy_buddies_ci.yml
@@ -70,6 +70,17 @@ jobs:
         with:
           name: coverage-out
           path: src/sample-app-test-go/coverage.out
+      
+      - name: Check code coverage
+        run: |
+          # Extract coverage percentage (assuming it's in the last line of test-report.txt)
+          COVERAGE=$(tail -n 1 src/sample-app-test-go/test-report.txt | grep coverage | awk '{print $2}')
+          COVERAGE_VALUE=${COVERAGE%?}  # Remove trailing % sign
+
+          if [[ $COVERAGE_VALUE -lt 60 ]]; then
+            echo "Code coverage ($COVERAGE_VALUE%) is below the threshold (60%). Failing job."
+            exit 1  # Fail the job
+          fi
 
   build-and-push-image-into-ecr:
     needs: unit-tests
