refactor(actions): :recycle: refactoring ci e cd

diff --git a/.github/workflows/deploy_buddies_cd.yml b/.github/workflows/deploy_buddies_cd.yml
--- a/.github/workflows/deploy_buddies_cd.yml
+++ b/.github/workflows/deploy_buddies_cd.yml
@@ -39,37 +39,37 @@ jobs:
         instance_ip=$(aws ec2 describe-instances --instance-ids "$instance_id" --query "Reservations[0].Instances[0].PublicIpAddress" --output text)
         echo "INSTANCE_IP=$instance_ip" >> $GITHUB_ENV
 
-    - name: Login to Amazon ECR
-      id: login-ecr
-      uses: aws-actions/amazon-ecr-login@v1
+    # - name: Login to Amazon ECR
+    #   id: login-ecr
+    #   uses: aws-actions/amazon-ecr-login@v1
 
-    - name: Determine IMAGE_TAG
-      id: set-tag
-      run: |
-        if [ "${{ github.event.inputs.action-type }}" == "release" ]; then
-          echo "IMAGE_TAG=latest" >> $GITHUB_ENV
-        elif [ "${{ github.event.inputs.action-type }}" == "rollback" ]; then
-          echo "IMAGE_TAG=rollback" >> $GITHUB_ENV
-        else
-          echo "IMAGE_TAG=unknown" >> $GITHUB_ENV
-        fi
+    # - name: Determine IMAGE_TAG
+    #   id: set-tag
+    #   run: |
+    #     if [ "${{ github.event.inputs.action-type }}" == "release" ]; then
+    #       echo "IMAGE_TAG=latest" >> $GITHUB_ENV
+    #     elif [ "${{ github.event.inputs.action-type }}" == "rollback" ]; then
+    #       echo "IMAGE_TAG=rollback" >> $GITHUB_ENV
+    #     else
+    #       echo "IMAGE_TAG=unknown" >> $GITHUB_ENV
+    #     fi
 
-    - name: Delete Existing Image
-      run: |
-        aws ecr batch-delete-image --repository-name builds --image-ids imageTag=$IMAGE_TAG || echo "No image found with tag $IMAGE_TAG, or deletion not required."
+    # - name: Delete Existing Image
+    #   run: |
+    #     aws ecr batch-delete-image --repository-name builds --image-ids imageTag=$IMAGE_TAG || echo "No image found with tag $IMAGE_TAG, or deletion not required."
 
-    - name: Verifies
-      run: |
-        echo "ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}"
-        echo "IMAGE_TAG=$IMAGE_TAG"
+    # - name: Verifies
+    #   run: |
+    #     echo "ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}"
+    #     echo "IMAGE_TAG=$IMAGE_TAG"
 
-    - name: Build the Docker image
-      run: |
-        docker build -t ${{ steps.login-ecr.outputs.registry }}/builds:$IMAGE_TAG -f src/server/Dockerfile src/server
+    # - name: Build the Docker image
+    #   run: |
+    #     docker build -t ${{ steps.login-ecr.outputs.registry }}/builds:$IMAGE_TAG -f src/server/Dockerfile src/server
 
-    - name: Push the Docker image to Amazon ECR
-      run: |
-        docker push ${{ steps.login-ecr.outputs.registry }}/builds:$IMAGE_TAG
+    # - name: Push the Docker image to Amazon ECR
+    #   run: |
+    #     docker push ${{ steps.login-ecr.outputs.registry }}/builds:$IMAGE_TAG
     
     - name: Set up SSH Connection
       run: |
